---
- name: determine if docker is installed
  command: which docker
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: get docker version
  shell: docker --version | awk '{ print $3 }'
  register: docker_installed_version
  when: docker_installed|success
  changed_when: false

- debug:
    var: docker_installed_version

- name: download docker
  get_url:
    url: https://releases.rancher.com/install-docker/{{ docker_version }}.sh
    dest: /tmp/{{ docker_version }}.sh
    mode: 0770
  when: not docker_installed|success or
        not docker_installed_version.stdout|search(docker_version|string)

- name: install or upgrade docker
  shell: sh /tmp/{{ docker_version }}.sh
  when: not docker_installed|success or
        not docker_installed_version.stdout|search(docker_version|string)

- name: delete docker installation script
  file:
    path: /tmp/{{ docker_version }}.sh
    state: absent
  when: not docker_installed|success or
        not docker_installed_version.stdout|search(docker_version|string)

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: add our login user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: force systemd to reread configs
  systemd:
    daemon_reload: yes
