- hosts: edge,service,master
  gather_facts: False
  pre_tasks:
    - name: Check if python is installed
      raw: which python
      register: python_installed
      ignore_errors: true
      changed_when: false

    - name: Installing python
      when: not python_installed|success
      become: True
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      ignore_errors: true
      changed_when: false

- hosts: edge,service,master
  roles:
      - { role: docker, become: True }
