- hosts: edge,service,master
  gather_facts: False
  pre_tasks:
    - name: Check if python is installed
      raw: which python
      retries: 3
      delay: 20
      register: python_present
      ignore_errors: true
      changed_when: false

    - name: Updating package lists
      when: not python_present|success
      become: True
      raw: apt-get -y update
      retries: 3
      delay: 20
      changed_when: false

    - name: Installing python
      when: not python_present|success
      become: True
      raw: apt-get -y install python-minimal
      retries: 3
      delay: 20
      changed_when: false

- hosts: edge,service,master
  roles:
      - { role: docker, become: True }
